services:
  mysql:
    image: mysql:8.0
    container_name: bankapp-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pTest@123"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - bankapp-nw

  bankapp:
    build: .
    container_name: bankapp
    ports:
      - "8000:8080"
    environment:
      MYSQL_HOST: bankapp-mysql
      MYSQL_PASSWORD: Test@123
      MYSQL_DATABASE: bankappdb
      MYSQL_PORT: 3306
      MYSQL_USER: root
      OLLAMA_URL: http://ollama:11434
    depends_on: 
      mysql:
        condition: service_healthy
    networks:
      - bankapp-nw   

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports: 
      - "11434:11434"
    networks: 
      - bankapp-nw
    volumes:
      - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 20s
      timeout: 10s
      retries: 5

 # Model loader (VERY IMPORTANT)        
  ollama-init:
    image: ollama/ollama
    container_name: ollama-init
    environment:
      - OLLAMA_HOST=ollama
    volumes:
      - ollama_data:/root/.ollama
    depends_on:
      ollama:
        condition: service_healthy
    entrypoint: /bin/sh
    command: -c "ollama pull tinyllama"
    networks:
      - bankapp-nw

networks:
  bankapp-nw:
    driver: bridge

volumes:
  mysql-data:
  ollama_data:
